CREATE TABLE IF NOT EXISTS board_user ( 
 id varchar(40) primary key,
 passwd varchar(40) not null,
 user_name varchar(30) not null,
 age integer not null,
 role varchar(15) not null
);

CREATE SEQUENCE seq;

CREATE TABLE IF NOT EXISTS board ( 
 seq integer generated by default as sequence seq primary key,
 title varchar(40) not null,
 content varchar(2000) not null,
 write_id varchar(40) not null,
 register_ymdt timestamp not null,
 file_real_name varchar(50),
 file_name varchar(50)
);

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('admin1', 'admin', '관리자1', 99, 'ADMIN');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('admin2', 'admin', '관리자2', 99, 'ADMIN');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('admin3', 'admin', '관리자3', 99, 'ADMIN');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('admin4', 'admin', '관리자4', 99, 'ADMIN');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user1', 'user', '유저1', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user2', 'user', '유저2', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user3', 'user', '유저3', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user4', 'user', '유저4', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user5', 'user', '유저5', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user6', 'user', '유저6', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user7', 'user', '유저7', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user8', 'user', '유저8', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user9', 'user', '유저9', 99, 'MEMBER');

INSERT INTO board_user
(id, passwd, user_name, age, role)
VALUES
('user10', 'user', '유저10', 99, 'MEMBER');

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목1', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목2', '내용', 'admin2', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목3', '내용', 'admin3', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목4', '내용', 'admin4', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목5', '내용', 'user1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목6', '내용', 'user1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목7', '내용', 'user1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목8', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목9', '내용', 'admin2', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목10', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목11', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목12', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목13', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목14', '내용', 'user2', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목15', '내용', 'user2', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목16', '내용', 'user2', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목17', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목18', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목19', '내용', 'admin1', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목20', '내용', 'user2', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목21', '내용', 'user2', CURRENT_TIMESTAMP);

INSERT
INTO board (title, content, write_id, register_ymdt)
VALUES ('제목22', '내용', 'user2', CURRENT_TIMESTAMP);